# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='批次编号')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '批次信息',
                'verbose_name_plural': '批次信息',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='品种名称')),
                ('created', models.DateField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '品种信息',
                'verbose_name_plural': '品种信息',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='重量')),
                ('long', models.IntegerField(null=True, verbose_name='长')),
                ('width', models.IntegerField(null=True, verbose_name='宽')),
                ('high', models.IntegerField(null=True, verbose_name='高')),
                ('m3', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='立方')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('cost_type', models.CharField(choices=[('1', '按重量'), ('2', '按立方')], default='1', max_length=1, verbose_name='出材率计算方式')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Batch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '荒料信息',
                'verbose_name_plural': '荒料信息',
            },
        ),
        migrations.CreateModel(
            name='Quarry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='矿口名称')),
                ('desc', models.CharField(max_length=200, verbose_name='描述信息')),
                ('created', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('updated', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '矿口信息',
                'verbose_name_plural': '矿口信息',
            },
        ),
    ]
