# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_type',
        ),
    ]
