# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_cost_type'),
        ('products', '0002_auto_20170606_0111'),
    ]

    operations = [
    ]
