# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_slab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slab',
            old_name='thick',
            new_name='thickness',
        ),
    ]
