# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170621_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slab',
            options={'verbose_name': '码单', 'verbose_name_plural': '码单'},
        ),
        migrations.AlterField(
            model_name='product',
            name='block_num',
            field=models.CharField(max_length=16, unique=True, verbose_name='荒料编号'),
        ),
        migrations.AlterField(
            model_name='slab',
            name='block_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slab', to='products.Product', verbose_name='荒料编号'),
        ),
    ]
