# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_auto_20170719_1049'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0010_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('block', '荒料'), ('coarse', '毛板'), ('slab', '板材')], max_length=6, verbose_name='形态')),
                ('object_id', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('address', models.ForeignKey(on_delete=models.SET(products.models.get_address_default), to='process.ServiceProvider', verbose_name='库存地址')),
            ],
            options={
                'verbose_name': '库存地址',
                'verbose_name_plural': '库存地址',
                'ordering': ('-updated',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_sell',
            field=models.BooleanField(default=False, verbose_name='是否已售'),
        ),
        migrations.AddField(
            model_name='slab',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='process.ServiceProvider', verbose_name='库存地址'),
        ),
        migrations.AddField(
            model_name='inventoryaddress',
            name='block_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='products.Product', verbose_name='荒料编号'),
        ),
        migrations.AddField(
            model_name='inventoryaddress',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
