# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170728_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sell',
        ),
    ]
