# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 02:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_remove_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '城市列表',
                'verbose_name_plural': '城市列表',
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('type', models.CharField(choices=[('personal', '个人'), ('company', '公司')], max_length=12, verbose_name='客户类型')),
                ('call', models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms'), ('cp', '公司')], max_length=12, verbose_name='称呼')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='联系电话')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后交易日期')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.City', verbose_name='城市')),
                ('data_entry_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerinfo_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据录入人')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '省份列表',
                'verbose_name_plural': '省份列表',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', '新订单'), ('V', '核实'), ('F', '完成'), ('C', '关闭'), ('M', '修改过')], default='N', max_length=1, verbose_name='订单状态')),
                ('order', models.CharField(db_index=True, default='new', max_length=16, unique=True, verbose_name='订单号')),
                ('date', models.DateField(db_index=True, verbose_name='订单日期')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('verify_date', models.DateField(db_index=True, verbose_name='审核日期')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.City', verbose_name='城市')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='sales.CustomerInfo', verbose_name='客户名称')),
                ('data_entry_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据录入人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Province', verbose_name='省份')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_verifier', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.SmallIntegerField(blank=True, null=True, verbose_name='夹数')),
                ('pic', models.SmallIntegerField(blank=True, null=True, verbose_name='件数')),
                ('thickness', models.CharField(blank=True, max_length=6, null=True, verbose_name='厚度')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='数量')),
                ('unit', models.CharField(choices=[('m2', 'm2'), ('m3', 'm3'), ('ton', 'ton')], max_length=4, verbose_name='单位')),
                ('block_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='products.Product', verbose_name='荒料编号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.SalesOrder', verbose_name='对应单号')),
            ],
            options={
                'verbose_name': '销售订单明细',
                'verbose_name_plural': '销售订单明细',
            },
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Province', verbose_name='省份'),
        ),
    ]
