# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='farther_id',
            field=models.SmallIntegerField(default=1, verbose_name='对应省份id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='province_id',
            field=models.SmallIntegerField(default=1, help_text='用于与市级联动', verbose_name='省份id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后交易日期'),
        ),
    ]
