# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170719_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='farther_id',
            new_name='father_id',
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
