# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170719_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='call',
            field=models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms'), ('cp', '公司')], default='mr', max_length=12, verbose_name='称呼'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='type',
            field=models.CharField(choices=[('personal', '个人'), ('company', '公司')], default='personal', max_length=12, verbose_name='客户类型'),
        ),
    ]
