# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20170721_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='单价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.City', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Province', verbose_name='省份'),
        ),
    ]
