# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20170721_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='数量'),
        ),
    ]
