# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20170722_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='单价'),
        ),
    ]
