# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20170722_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='block_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='products.Product', verbose_name='荒料编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='pic',
            field=models.SmallIntegerField(default=1, verbose_name='件数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='单价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='数量'),
            preserve_default=False,
        ),
    ]
