# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_auto_20170728_1728'),
        ('sales', '0009_auto_20170722_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='账户名称')),
                ('bank_name', models.CharField(max_length=10, verbose_name='银行名称')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账户信息',
                'verbose_name_plural': '账户信息',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderPickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_num', models.CharField(max_length=10, verbose_name='提货车牌')),
                ('consignee', models.CharField(max_length=10, verbose_name='提货人')),
                ('date', models.DateField(db_index=True, verbose_name='提货日期')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_entry_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderpickup_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据录入人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='sales.SalesOrder', verbose_name='对应销售单')),
            ],
            options={
                'verbose_name': '销售提货单',
                'verbose_name_plural': '销售提货单',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderPickUpCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('P', '打木夹'), ('L', '裝车'), ('M', '木方'), ('O', '其它')], max_length=1, verbose_name='项目')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='金额')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_entry_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderpickupcost_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据录入人')),
            ],
            options={
                'verbose_name': '提货费用',
                'verbose_name_plural': '提货费用',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderPickUpItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.SmallIntegerField(blank=True, null=True, verbose_name='夹数')),
                ('pic', models.SmallIntegerField(verbose_name='件数')),
                ('thickness', models.CharField(blank=True, max_length=6, null=True, verbose_name='厚度')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='数量')),
                ('unit', models.CharField(choices=[('m2', 'm2'), ('m3', 'm3'), ('ton', 'ton')], max_length=4, verbose_name='单位')),
                ('block_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_item', to='products.Product', verbose_name='荒料编号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.SalesOrderPickUp', verbose_name='对应单号')),
            ],
            options={
                'verbose_name': '提货明细',
                'verbose_name_plural': '提货明细',
            },
        ),
        migrations.CreateModel(
            name='SalesProceeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='金额')),
                ('type', models.CharField(choices=[('E', '订金'), ('G', '货款')], default='g', max_length=1, verbose_name='款项类型')),
                ('method', models.CharField(choices=[('T', '转账'), ('C', '现金'), ('B', '冲账')], max_length=1, verbose_name='支付方式')),
                ('date', models.DateField(db_index=True, verbose_name='支付日期')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.ProceedsAccount')),
                ('data_entry_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesproceeds_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据录入人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceeds', to='sales.SalesOrder', verbose_name='对应销售单')),
            ],
            options={
                'verbose_name': '销售订单收款记录',
                'verbose_name_plural': '销售订单收款记录',
            },
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='单价'),
        ),
    ]
