# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20170805_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderpickupcost',
            name='data_entry_staff',
        ),
        migrations.AddField(
            model_name='salesorderpickupcost',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_cost', to='sales.SalesOrder', verbose_name='对应销售单'),
            preserve_default=False,
        ),
    ]
