# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20170808_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderpickupcost',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='sales.SalesOrderPickUp', verbose_name='对应单号'),
        ),
    ]
