# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0014_auto_20170808_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExtraCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('discount', '折扣'), ('brokerage', '回扣'), ('shortage', '少收'), ('compensate', '补偿'), ('bad_debt', '坏账'), ('other', '其他')], max_length=10, verbose_name='项目')),
                ('desc', models.CharField(blank=True, max_length=80, null=True, verbose_name='补充说明')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金额')),
                ('date', models.DateField(verbose_name='日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_entry_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderextracost_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据录入人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderextracost_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '额外费用',
                'verbose_name_plural': '额外费用',
            },
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ('-status', '-order'), 'verbose_name': '销售订单', 'verbose_name_plural': '销售订单'},
        ),
        migrations.AlterModelOptions(
            name='salesorderpickup',
            options={'ordering': ['date'], 'verbose_name': '销售提货单', 'verbose_name_plural': '销售提货单'},
        ),
        migrations.AlterField(
            model_name='proceedsaccount',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='账户名称'),
        ),
        migrations.AlterField(
            model_name='salesproceeds',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.ProceedsAccount', verbose_name='收款账户'),
        ),
        migrations.AddField(
            model_name='orderextracost',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_cost', to='sales.SalesOrder', verbose_name='对应销售单'),
        ),
    ]
