# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksorderitem',
            name='think',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='厚度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ksorderitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='mborderitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='processorder',
            name='order_type',
            field=models.CharField(choices=[('TS', '运输单'), ('MB', '补板单'), ('KS', '界石单'), ('ST', '荒料入库单')], max_length=2, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(choices=[('TS', '运输'), ('MB', '补板'), ('KS', '界石')], max_length=2, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='storderitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='tsorderitem',
            name='be_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TS_from', to='process.ServiceProvider', verbose_name='起始地'),
        ),
        migrations.AlterField(
            model_name='tsorderitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='tsorderitem',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TS_to', to='process.ServiceProvider', verbose_name='目的'),
        ),
    ]
