# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20170621_1534'),
        ('process', '0004_auto_20170620_2237'),
    ]

    operations = [
    ]
