# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_merge_20170704_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsorderitem',
            name='block_type',
            field=models.CharField(choices=[('block', '荒料'), ('coarse', '毛板'), ('slab', '板材')], max_length=6, verbose_name='形态'),
        ),
    ]
