# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20170704_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slablist',
            name='ps',
        ),
        migrations.RemoveField(
            model_name='slablist',
            name='thickness',
        ),
        migrations.AlterField(
            model_name='ksorderitem',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='mborderitem',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='storderitem',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='tsorderitem',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
