# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20170709_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slablist',
            name='order_item',
        ),
    ]
