# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_auto_20170719_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processorder',
            options={'ordering': ['-updated'], 'verbose_name': '加工订单', 'verbose_name_plural': '加工订单'},
        ),
    ]
