# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purchase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(db_index=True, default='a', max_length=16, unique=True, verbose_name='订单号')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(default='IM', max_length=2, verbose_name='订单类型')),
                ('container', models.IntegerField(null=True, verbose_name='货柜数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='单价')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='下单日期')),
                ('data_entry_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据录入人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '进口代理订单',
                'verbose_name_plural': '进口代理订单',
            },
        ),
        migrations.CreateModel(
            name='ImportOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='重量')),
                ('block_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_order', to='products.Product', verbose_name='荒料编号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='purchase.ImportOrder', verbose_name='进口代理订单')),
            ],
            options={
                'verbose_name': '进口代理单明细',
                'verbose_name_plural': '进口代理单明细',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=16, verbose_name='订单号')),
                ('date', models.DateField(verbose_name='日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金额')),
                ('use_type', models.CharField(choices=[('tt', 'TT'), ('lc', 'LC'), ('freight', '运费'), ('advance', '预付款'), ('kickback', '佣金')], max_length=16, verbose_name='款项用途')),
                ('payee_account', models.CharField(max_length=20, verbose_name='收款人账户')),
                ('usd_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='美金金额')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='汇率')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('file', models.FileField(blank=True, null=True, upload_to=purchase.models.get_upload_to, verbose_name='相关文件')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_entry_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据录入人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '付款记录',
                'verbose_name_plural': '付款记录',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(db_index=True, default='a', max_length=16, unique=True, verbose_name='订单号')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(default='PC', max_length=2, verbose_name='订单类型')),
                ('data_entry_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据录入人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='荒料编号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='purchase.PurchaseOrder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '采购订单明细',
                'verbose_name_plural': '采购订单明细',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trade', '贸易公司'), ('quarry', '矿山'), ('shipping', '进口代理')], max_length=12, verbose_name='供应商类型')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '供应商资料',
                'verbose_name_plural': '供应商资料',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order', to='purchase.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payee',
            field=models.ForeignKey(on_delete=models.SET(purchase.models.payee_setdefault), to='purchase.Supplier', verbose_name='收款人'),
        ),
        migrations.AddField(
            model_name='importorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_order', to='purchase.Supplier', verbose_name='供应商'),
        ),
    ]
