# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 00:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import purchase.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=purchase.models.file_get_upload_to, verbose_name='相关文件'),
        ),
        migrations.AddField(
            model_name='importorder',
            name='ps',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cost_money',
            field=models.CharField(choices=[('USD', '$美元'), ('CNY', '￥人民币'), ('EUR', '€欧元')], default='USD', max_length=8, verbose_name='结算货币'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 8, 55, 3, 226136), verbose_name='采购日期'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=purchase.models.file_get_upload_to, verbose_name='相关文件'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ps',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='order',
            field=models.CharField(db_index=True, default='new', max_length=16, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order',
            field=models.CharField(db_index=True, default='new', max_length=16, unique=True, verbose_name='订单号'),
        ),
    ]
