# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20170606_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 1, 26, 13, 217280, tzinfo=utc), verbose_name='采购日期'),
        ),
    ]
