# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20170606_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='采购日期'),
        ),
    ]
