# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20170606_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='cost_by',
            field=models.CharField(choices=[('ton', '按重量'), ('m3', '按立方')], default='ton', max_length=4, verbose_name='成本计算方式'),
        ),
    ]
