# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20170607_2304'),
        ('purchase', '0007_auto_20170608_1452'),
    ]

    operations = [
    ]
