# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_purchaseorderextracost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default='django.utils.timezone.now', verbose_name='采购日期'),
        ),
    ]
