# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_auto_20170704_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(verbose_name='采购日期'),
        ),
    ]
